export let questions = [
    {
        questionText:'Rustom&nbsp;is a Medium Altitude Long Endurance unmanned air vehicle (UAV) being developed by the _________.',
        answers:[
            {
                answerText:'50',
                correctAnswer:true,
            },
            {
                answerText:'60',
                correctAnswer:false,
            },
            {
                answerText:'55',
                correctAnswer:false,
            },
            {
                answerText:'65',
                correctAnswer:false,
            },
        ]
    },
    {
        questionText:'What is your gaga?',
        answers:[
            {
                answerText:'50',
                correctAnswer:false,
            },
            {
                answerText:'60',
                correctAnswer:true,
            },
            {
                answerText:'55',
                correctAnswer:false,
            },
            {
                answerText:'65',
                correctAnswer:false,
            },
        ]
    },
    {
        questionText:'What is 3434 name?',
        answers:[
            {
                answerText:'50',
                correctAnswer:false,
            },
            {
                answerText:'60',
                correctAnswer:true,
            },
            {
                answerText:'55',
                correctAnswer:false,
            },
            {
                answerText:'65',
                correctAnswer:false,
            },
        ]
    },
    {
        questionText:'What is your na12312me?',
        answers:[
            {
                answerText:'50',
                correctAnswer:false,
            },
            {
                answerText:'60',
                correctAnswer:true,
            },
            {
                answerText:'55',
                correctAnswer:false,
            },
            {
                answerText:'65',
                correctAnswer:false,
            },
        ]
    },
    {
        questionText:'What is your name?',
        answers:[
            {
                answerText:'50',
                correctAnswer:false,
            },
            {
                answerText:'60',
                correctAnswer:true,
            },
            {
                answerText:'55',
                correctAnswer:false,
            },
            {
                answerText:'65',
                correctAnswer:false,
            },
        ]
    },
    {
        questionText:'What is your name?',
        answers:[
            {
                answerText:'50',
                correctAnswer:false,
            },
            {
                answerText:'60',
                correctAnswer:true,
            },
            {
                answerText:'55',
                correctAnswer:false,
            },
            {
                answerText:'65',
                correctAnswer:false,
            },
        ]
    },
    {
        questionText:'What is your name?',
        answers:[
            {
                answerText:'50',
                correctAnswer:false,
            },
            {
                answerText:'60',
                correctAnswer:true,
            },
            {
                answerText:'55',
                correctAnswer:false,
            },
            {
                answerText:'65',
                correctAnswer:false,
            },
        ]
    },
    {
        questionText:'What is your name?',
        answers:[
            {
                answerText:'50',
                correctAnswer:false,
            },
            {
                answerText:'60',
                correctAnswer:true,
            },
            {
                answerText:'55',
                correctAnswer:false,
            },
            {
                answerText:'65',
                correctAnswer:false,
            },
        ]
    },
    {
        questionText:'What is your name?',
        answers:[
            {
                answerText:'50',
                correctAnswer:false,
            },
            {
                answerText:'60',
                correctAnswer:true,
            },
            {
                answerText:'55',
                correctAnswer:false,
            },
            {
                answerText:'65',
                correctAnswer:false,
            },
        ]
    },
    {
        questionText:'What is your name?',
        answers:[
            {
                answerText:'50',
                correctAnswer:false,
            },
            {
                answerText:'60',
                correctAnswer:true,
            },
            {
                answerText:'55',
                correctAnswer:false,
            },
            {
                answerText:'65',
                correctAnswer:false,
            },
        ]
    },
    {
        questionText:'What is adf324 name?',
        answers:[
            {
                answerText:'50',
                correctAnswer:false,
            },
            {
                answerText:'60',
                correctAnswer:true,
            },
            {
                answerText:'55',
                correctAnswer:false,
            },
            {
                answerText:'65',
                correctAnswer:false,
            },
        ]
    },
    {
        questionText:'What is asdf name?',
        answers:[
            {
                answerText:'50',
                correctAnswer:false,
            },
            {
                answerText:'60',
                correctAnswer:true,
            },
            {
                answerText:'55',
                correctAnswer:false,
            },
            {
                answerText:'65',
                correctAnswer:false,
            },
        ]
    },
    {
        questionText:'What is your name?',
        answers:[
            {
                answerText:'50',
                correctAnswer:false,
            },
            {
                answerText:'60',
                correctAnswer:true,
            },
            {
                answerText:'55',
                correctAnswer:false,
            },
            {
                answerText:'65',
                correctAnswer:false,
            },
        ]
    },
    
]